version: '3.8'
services:
#  nest-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: nest-api
#    restart: always
#    ports:
#      - "4001:4001"
#    depends_on:
#      - postgres
#    env_file:
#      - .env

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    name: nest-prisma-docker-db
